"""add tags and icon to certificate

Revision ID: 17ad55fb99cc
Revises: 70f87b652a5a
Create Date: 2026-05-06 16:57:30.867114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ad55fb99cc'
down_revision = '70f87b652a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('icon')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
