"""add short_description to project

Revision ID: 8399102338c1
Revises: aa3f1ee2d463
Create Date: 2026-02-04 21:57:09.357624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8399102338c1'
down_revision = 'aa3f1ee2d463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###
